// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.0
// source: src/proto/department-service.proto

package department

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int32                  `protobuf:"varint,1,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonRequest) Reset() {
	*x = ListPersonRequest{}
	mi := &file_src_proto_department_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonRequest) ProtoMessage() {}

func (x *ListPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_department_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonRequest.ProtoReflect.Descriptor instead.
func (*ListPersonRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_department_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListPersonRequest) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type ListPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Income        int32                  `protobuf:"varint,4,opt,name=income,proto3" json:"income,omitempty"`
	DepartmentId  int32                  `protobuf:"varint,5,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonResponse) Reset() {
	*x = ListPersonResponse{}
	mi := &file_src_proto_department_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonResponse) ProtoMessage() {}

func (x *ListPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_department_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonResponse.ProtoReflect.Descriptor instead.
func (*ListPersonResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_department_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListPersonResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListPersonResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListPersonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPersonResponse) GetIncome() int32 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *ListPersonResponse) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

var File_src_proto_department_service_proto protoreflect.FileDescriptor

const file_src_proto_department_service_proto_rawDesc = "" +
	"\n" +
	"\"src/proto/department-service.proto\x12\n" +
	"department\"7\n" +
	"\x11ListPersonRequest\x12\"\n" +
	"\fdepartmentId\x18\x01 \x01(\x05R\fdepartmentId\"\x8a\x01\n" +
	"\x12ListPersonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06income\x18\x04 \x01(\x05R\x06income\x12\"\n" +
	"\fdepartmentId\x18\x05 \x01(\x05R\fdepartmentId2b\n" +
	"\x11DepartmentService\x12M\n" +
	"\n" +
	"ListPerson\x12\x1d.department.ListPersonRequest\x1a\x1e.department.ListPersonResponse0\x01B\x15Z\x13./src/pb/departmentb\x06proto3"

var (
	file_src_proto_department_service_proto_rawDescOnce sync.Once
	file_src_proto_department_service_proto_rawDescData []byte
)

func file_src_proto_department_service_proto_rawDescGZIP() []byte {
	file_src_proto_department_service_proto_rawDescOnce.Do(func() {
		file_src_proto_department_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_department_service_proto_rawDesc), len(file_src_proto_department_service_proto_rawDesc)))
	})
	return file_src_proto_department_service_proto_rawDescData
}

var file_src_proto_department_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_proto_department_service_proto_goTypes = []any{
	(*ListPersonRequest)(nil),  // 0: department.ListPersonRequest
	(*ListPersonResponse)(nil), // 1: department.ListPersonResponse
}
var file_src_proto_department_service_proto_depIdxs = []int32{
	0, // 0: department.DepartmentService.ListPerson:input_type -> department.ListPersonRequest
	1, // 1: department.DepartmentService.ListPerson:output_type -> department.ListPersonResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_department_service_proto_init() }
func file_src_proto_department_service_proto_init() {
	if File_src_proto_department_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_department_service_proto_rawDesc), len(file_src_proto_department_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_department_service_proto_goTypes,
		DependencyIndexes: file_src_proto_department_service_proto_depIdxs,
		MessageInfos:      file_src_proto_department_service_proto_msgTypes,
	}.Build()
	File_src_proto_department_service_proto = out.File
	file_src_proto_department_service_proto_goTypes = nil
	file_src_proto_department_service_proto_depIdxs = nil
}
